import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "../components/common/card";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Swing</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Card content="content" image="img" profile="profile" />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
